esmini:
  window: 60 60 800 400
  osc: ./resources/xosc/cut-in.xosc

replayer:
  window: 60 60 800 400
  res_path: ./resources
  file: sim.dat
  
odrviewer:
  window: 60 60 800 400
  odr: ./resources/xodr/straight_500m.xodr